<?php
add_action('acf/init', 'my_acf_blocks_init');
function my_acf_blocks_init() {

    // Check function exists.
    if( function_exists('acf_register_block_type') ) {

        // Register a testimonial block.
       acf_register_block_type(array(
    'name' => 'block-example',
    'title' => 'Block Example',
    'active' => true,
    'description' => '',
    'category' => 'common',
    'icon' => '',
    'keywords' => array(),
    'post_types' => array(),
    'mode' => 'edit',
    'align' => '',
    'align_text' => '',
    'align_content' => 'top',
    'render_template' => '/blocks/block-example/block-example.php',
    'render_callback' => '',
    'enqueue_style' => '',
    'enqueue_script' => '',
    'enqueue_assets' => '',
    'supports' => array(
        'anchor' => true,
        'align' => true,
        'align_text' => false,
        'align_content' => false,
        'full_height' => false,
        'mode' => true,
        'multiple' => true,
        'example' => array(),
        'jsx' => true,
    ),
));

acf_register_block_type(array(
    'name' => 'block-gallery-section',
    'title' => 'Block Gallery Section',
    'active' => true,
    'description' => '',
    'category' => 'bunny-category',
    'icon' => array(
        'background' => '',
        'foreground' => '#8224e3',
        'src' => 'images-alt2',
    ),
    'keywords' => array(),
    'post_types' => array(),
    'mode' => 'edit',
    'align' => '',
    'align_text' => '',
    'align_content' => 'top',
    'render_template' => '/blocks/gallery/block-gallery-section.php',
    'render_callback' => '',
    'enqueue_style' => '',
    'enqueue_script' => '',
    'enqueue_assets' => '',
    'supports' => array(
        'anchor' => true,
        'align' => true,
        'align_text' => false,
        'align_content' => false,
        'full_height' => false,
        'mode' => true,
        'multiple' => true,
        'example' => array(),
        'jsx' => false,
    ),
));

acf_register_block_type(array(
    'name' => 'block-icon-grid',
    'title' => 'Block Icon Grid',
    'active' => true,
    'description' => '',
    'category' => 'common',
    'icon' => array(
        'background' => '',
        'foreground' => '#8224e3',
        'src' => 'info',
    ),
    'keywords' => array(),
    'post_types' => array(),
    'mode' => 'edit',
    'align' => '',
    'align_text' => '',
    'align_content' => 'top',
    'render_template' => '/blocks/icon-grid/block-icon-grid.php',
    'render_callback' => '',
    'enqueue_style' => '',
    'enqueue_script' => '',
    'enqueue_assets' => '',
    'supports' => array(
        'anchor' => true,
        'align' => true,
        'align_text' => false,
        'align_content' => false,
        'full_height' => false,
        'mode' => true,
        'multiple' => true,
        'example' => array(),
        'jsx' => false,
    ),
));

acf_register_block_type(array(
    'name' => 'block-page-scroll',
    'title' => 'Block Page Scroll',
    'active' => true,
    'description' => '',
    'category' => 'common',
    'icon' => array(
        'background' => '',
        'foreground' => '#8224e3',
        'src' => 'move',
    ),
    'keywords' => array(),
    'post_types' => array(),
    'mode' => 'edit',
    'align' => '',
    'align_text' => '',
    'align_content' => 'top',
    'render_template' => '/blocks/scroll/block-page-scroll.php',
    'render_callback' => '',
    'enqueue_style' => '',
    'enqueue_script' => '',
    'enqueue_assets' => '',
    'supports' => array(
        'anchor' => true,
        'align' => true,
        'align_text' => false,
        'align_content' => false,
        'full_height' => false,
        'mode' => true,
        'multiple' => true,
        'example' => array(),
        'jsx' => false,
    ),
));

acf_register_block_type(array(
    'name' => 'block-simple-hero',
    'title' => 'Block Simple Hero',
    'active' => true,
    'description' => '',
    'category' => 'common',
    'icon' => array(
        'background' => '',
        'foreground' => '#8224e3',
        'src' => 'images-alt2',
    ),
    'keywords' => array(),
    'post_types' => array(),
    'mode' => 'edit',
    'align' => '',
    'align_text' => '',
    'align_content' => 'top',
    'render_template' => '/blocks/hero/block-simple-hero.php',
    'render_callback' => '',
    'enqueue_style' => '',
    'enqueue_script' => '',
    'enqueue_assets' => '',
    'supports' => array(
        'anchor' => true,
        'align' => true,
        'align_text' => false,
        'align_content' => false,
        'full_height' => false,
        'mode' => true,
        'multiple' => true,
        'example' => array(),
        'jsx' => false,
    ),
));

acf_register_block_type(array(
    'name' => 'block-simple-text-and-image',
    'title' => 'Block Simple Text and Image',
    'active' => true,
    'description' => '',
    'category' => 'common',
    'icon' => array(
        'background' => '',
        'foreground' => '#8224e3',
        'src' => 'media-text',
    ),
    'keywords' => array(),
    'post_types' => array(),
    'mode' => 'edit',
    'align' => '',
    'align_text' => '',
    'align_content' => 'top',
    'render_template' => '/blocks/block-text/simple-text-and-image.php',
    'render_callback' => '',
    'enqueue_style' => '',
    'enqueue_script' => '',
    'enqueue_assets' => '',
    'supports' => array(
        'anchor' => true,
        'align' => true,
        'align_text' => false,
        'align_content' => false,
        'full_height' => false,
        'mode' => true,
        'multiple' => true,
        'example' => array(),
        'jsx' => false,
    ),
));

acf_register_block_type(array(
    'name' => 'block-simple-post-type',
    'title' => 'Block Simple Post Type',
    'active' => true,
    'description' => '',
    'category' => 'common',
    'icon' => array(
        'background' => '',
        'foreground' => '#8224e3',
        'src' => 'media-text',
    ),
    'keywords' => array(),
    'post_types' => array(),
    'mode' => 'edit',
    'align' => '',
    'align_text' => '',
    'align_content' => 'top',
    'render_template' => '/blocks/block-post-type/simple-post-type.php',
    'render_callback' => '',
    'enqueue_style' => '',
    'enqueue_script' => '',
    'enqueue_assets' => '',
    'supports' => array(
        'anchor' => true,
        'align' => true,
        'align_text' => false,
        'align_content' => false,
        'full_height' => false,
        'mode' => true,
        'multiple' => true,
        'example' => array(),
        'jsx' => false,
    ),
));

acf_register_block_type(array(
    'name' => 'block-vertical-slider',
    'title' => 'Block Vertical Slider',
    'active' => true,
    'description' => '',
    'category' => 'common',
    'icon' => array(
        'background' => '',
        'foreground' => '#8224e3',
        'src' => 'images-alt2',
    ),
    'keywords' => array(),
    'post_types' => array(),
    'mode' => 'edit',
    'align' => '',
    'align_text' => '',
    'align_content' => 'top',
    'render_template' => '/blocks/vertical/block-vertical-slider.php',
    'render_callback' => '',
    'enqueue_style' => '',
    'enqueue_script' => '/blocks/vertical/block-vertical-slider.js',
    'enqueue_assets' => '',
    'supports' => array(
        'anchor' => true,
        'align' => true,
        'align_text' => false,
        'align_content' => false,
        'full_height' => false,
        'mode' => false,
        'multiple' => true,
        'example' => array(),
        'jsx' => false,
    ),
));

    }
}

add_action('acf/init', 'my_acf_op_init');
function my_acf_op_init() {

    // Check function exists.
    if( function_exists('acf_add_options_page') ) {

        // Add parent.
       $option_page = acf_add_options_page(array(
            'menu_slug' => 'global-site-settings',
            'page_title' => 'Global Site Settings',
            'active' => true,
            'menu_title' => 'Global Site',
            'capability' => 'edit_posts',
            'parent_slug' => '',
            'position' => 8,
            'icon_url' => 'dashicons-carrot',
            'redirect' => true,
            'post_id' => 'options',
            'autoload' => false,
            'update_button' => 'Update',
            'updated_message' => 'Options Updated',
        )); 
    }
}